### ISSUE TITLE
It's not Working

### ISSUE THREAD

**Issue by Medullitus** [moremeyou/Obsidian-Tag-Buddy#13]
When clicking a tag nothing happens, i tried ctrl + left click option too.

**Comment by moremeyou** [comment]
Hi there,
Thanks for your message. Can I confirm you're in Preview mode? Most Tag
Buddy functions only work in preview mode. No plans ot make the work in
edit mode as those most functions already exist there.

If you are in Preview mode, can you provide your obsidian version and what
version of the plugin you are using? Maybe even a sample of the note you're
trying to use it with.
D

**Comment by codey-badger** [comment]
Not working on mobile either. Showed a message that ask for reporting it but I don't remember the details.
