### ISSUE TITLE
Does this plugin conflict with [Obsidian-Tasks](https://github.com/obsidian-tasks-group/obsidian-tasks)?

### ISSUE THREAD

**Issue by kevin-yyy** [moremeyou/Obsidian-Tag-Buddy#15]
When I open a file which contains code blocks of obsidian-tasks plugin, it always pops a notice like this:![Notice](https://github.com/user-attachments/assets/9ec6e0dc-d3de-4785-89b0-760d4c644f6d)  
how can I cancel it? Is there any conflicts between the plugin and obsidian-task?

**Comment by tb-1212** [comment]
I also have this problem!

**Comment by moremeyou** [comment]
Thanks for sharing! I had this problem during testing all the different
formatting options. I thought I had fixed it, but added that notice in case
there was some new or unexpected note format that my tag processing
couldn't parse.

Good news, I have code in place to debug that issue. But I'll need a copy
of the note that's causing the issue? Would it be possible to strip out any
personal info and send me a copy? I might not need the plugin list if I get
the error too.  If not I'll need a list of your other installed plugins, or
any plugin that affects tags or the preview/reading mode.

Sorry for the annoying notice. Thrilled you're using the plugin :)
D

**Comment by gypsyav** [comment]
I'm having this problem too.  It seems to be occurring on pages with Tasks queries where the tags are on the list generated by the query.

**Comment by moremeyou** [comment]
I used Tasks too. Would it be possible for you to send me a copy of that note? You can upload it to chatgpt and ask it to make all the content gibberish.
I'd love to get to the bottom of this.

**Comment by moremeyou** [comment]
I will be looking at this this week.
D

**Comment by moremeyou** [comment]
Can you send me this .MD file? It's not parsing properly through email and
I want to make sure I'm testing it correctly.

Small update, I've narrowed down part (or possibly all) of the problem to
using TAB spaces. Use a TAB before a tag and it stops being recognized as a
tag... for now this seems like an Obsidian issue as I've tested this in a
clean sandbox vault. TabBuddy might be able to work around this issue. But
I'd like to test with your raw .MD file as well.

D

**Comment by gypsyav** [comment]
[2024-11-23 Sat.md](https://github.com/user-attachments/files/17951957/2024-11-23.Sat.md)

Hope this works.
