### ISSUE TITLE
Can not delete tags  in reading mode

### ISSUE THREAD

**Issue by francisHugo** [moremeyou/Obsidian-Tag-Buddy#6]
Hi,

This is a great plugin!

I can add tags in reading mode, but can not delete it.

I had tag wrangle plugin enabled, whenever I use ctl+click, it pops tag wrangle plugin's function, to let me create a tag note.

BR
FH

**Comment by francisHugo** [comment]
whether change the settings or not, it keeps not work. I disabled tag wrangler plugin, it still did not work. Seems no relative to tag wrangler.

**Comment by francisHugo** [comment]
Thanks for your quickly reply.

I think is the plugins I installed cause the issue. I tested in a new vault and it works perfectly!

it is realy a great plugin! I like it. 

Thanks again.

**Comment by moremeyou** [comment]
Thanks! Glad to hear! 
Would be great to hear what other plugins you had installed.
David
