### ISSUE TITLE
request of authorisation for translation

### ISSUE THREAD

**Issue by chenghuang-coder** [moremeyou/Obsidian-Tag-Buddy#7]
Hello, I'm a OB user from China, I've encountered your wonderful plugin when I was looking for a plugin that summerary the tags across the files!

I'd like to request your authorisation for translation of your readme into Chinese for a PKM-forcused community `pkmer.cn` in order to help those who are not able to read English doc with diffculty.

Looking forward to your reply. Thank you for your wonderful plugin!

yours,

HUANG Cheng

**Comment by chenghuang-coder** [comment]
p.s.
I will surely reserve your github project link in the very beginning of the zh. ver..
And a little modification in term of todo list and installation tips to avoid too much distraction.

**Comment by moremeyou** [comment]
Hi there,
Sounds like a good idea. But I'm not familiar with the process. Do I host the translated readme? Or how do they see it when searching the plugins? Also consider the settings are also in English as well as all the notices. I have plans to separate those out into a separate LOC file. But not a few months.

**Comment by chenghuang-coder** [comment]
Great to have your reply!
Maybe we can make it like this:

I shall send u the zh. ver. via email so that u can add it to ur readme in github,  and as long as there is any modification in readme, I shall update the translation. 
And I will also post the zh. ver. on pkmer.cn, a CN community of pkm(personal knowledge management) which contains lots of plugin contributors and pkm software amateurs.
As for settings, I've got some advices for u to impvore the order of readme maybe?

What do u think of that?

**Comment by chenghuang-coder** [comment]
by the way, there're some points that I found in need of modification in readme
1. in usage 4, u've written `Convert tags to text` which doesn't correspond to `Convert to tag text` in the settings, which causes confusion, maybe u've misplaced the word `to` in setting text? 
2. in usage 6, why the image is placed after the words, while is the opposite case in the other usages?
3. image of Usage 8 needs update because now we have 4 buttons (`creat new note` and `bake in active note` have been seperated)
4. I strong suggest that u rearrange the order in the `setting` section in readme so as to correspond to the order of the settings of the plugin in OB

Thx for reading!

**Comment by moremeyou** [comment]
Hey thanks for this. Will get back into it this month.
Hope all is well.
D
